CI: Fix Meson mixup between Conda and system Python headers (#839)
* use Conda Meson instead of system Meson

Otherwise, Meson insists on getting Cython to include system Python
headers which simply doesn't work:

	-----
	Sanity check compile stderr:
	In file included from /usr/include/python3.10/Python.h:8,
	                 from sanity_check_for_cython.c:19:
	/usr/include/python3.10/pyconfig.h:9:12: fatal error: aarch64-linux-gnu/python3.10/pyconfig.h: No such file or directory
	    9 | #  include <aarch64-linux-gnu/python3.10/pyconfig.h>
	      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	compilation terminated.

	-----

Also, avoid starting a new shell!

* Create the `test` env

* Different strategy: get rid of Conda altogther

Conda was used to get GCC or Clang for compiling the C extensions.
GitHub Actions runners come with C/C++ compilers pre-installed.