use Conda Meson instead of system Meson
Otherwise, Meson insists on getting Cython to include system Python
headers which simply doesn't work:

	-----
	Sanity check compile stderr:
	In file included from /usr/include/python3.10/Python.h:8,
	                 from sanity_check_for_cython.c:19:
	/usr/include/python3.10/pyconfig.h:9:12: fatal error: aarch64-linux-gnu/python3.10/pyconfig.h: No such file or directory
	    9 | #  include <aarch64-linux-gnu/python3.10/pyconfig.h>
	      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	compilation terminated.

	-----

Also, avoid starting a new shell!